### ISSUE TITLE
grafana dashboard file

### ISSUE THREAD

**Issue by rbosneag** [timoa/app-stores-prometheus-exporter#1]
Would you mind sharing in the repo the `json` for the Grafana dashboard? 
It's complete enough and it will speed up new users to get a complete visualisation.

Great job with this exporter, thank you!

**Comment by r3ddi** [comment]
Yeah it would be great if your share die Dashboard

**Comment by rbosneag** [comment]
Can you put your version of the dashboard, the one from the screenshot?
I will update it soon.

Offtopic: I found a simpler way to use custom _apps.js_ and _config.js_ files using Docker volumes, no need to rebuild the image. I will update the Readme if it's ok with you.

**Comment by timoa** [comment]
@rbosneag @r3ddi Thanks, guys!

I will make these dashboards public on Grafana.

Good idea for the Docker volume @rbosneag! I was running it for a while without Docker and it's clearly a better idea :)

I will update the README when shared the Grafana dashboards.

**Comment by Dudesons** [comment]
@timoa Can you share the json file meanwhile you publish the dashboard on grafana ?

**Comment by timoa** [comment]
I just published the first dashboard (per app metrics): https://grafana.com/dashboards/10100

I have more dashboards coming :)

 At my current job, I'm monitoring 22 apps (iOS/Android) including:

Number of reviews since the first release:
![Screen Shot 2019-04-25 at 13 44 20](https://user-images.githubusercontent.com/1432989/56736565-62958c00-6760-11e9-9698-0c1ffc8a247a.png)

Current score for the current release (bug on iOS):
![Screen Shot 2019-04-25 at 13 44 34](https://user-images.githubusercontent.com/1432989/56736569-65907c80-6760-11e9-8918-9f6744f98ce4.png)

Current version in iTunes and Google Play:
![Screen Shot 2019-04-25 at 13 44 44](https://user-images.githubusercontent.com/1432989/56736573-675a4000-6760-11e9-8230-fc1c2cac4575.png)

**Comment by timoa** [comment]
@rbosneag @r3ddi @Dudesons 
Hi guys!
It took me a while to share the Grafana dashboards since I wanted to improve some feature of the Prometheus Exporter and make the dashboard generics (and worked to other projects).

It's done now! You can download them here:
https://grafana.com/orgs/timoa/dashboards

I will update the README with the link to each dashboard now.
