### ISSUE TITLE
Got "Not Found" with curl.

### ISSUE THREAD

**Issue by datton94** [timoa/app-stores-prometheus-exporter#6]
Hi,
I have tried to install both via host and Docker, but I alway get "Not found" at all with curl http://localhost:9514 

The configuration file is your example config files, they were copied to config directory. 

So, did I do something wrong?

**Comment by timoa** [comment]
Hey @datton94!

I got the same issue when it's been a while that I haven't work on this project :)

It's because the standard endpoint for a Prometheus Exporter is `/metrics`.

The right URL is http://localhost:9514/metrics.

It sends a 404 Not Found for all the other endpoints. I will update the error page for something more explicit.

**Comment by timoa** [comment]
I added an HTML page for the 404 errors + a link to the `/metrics` endpoint (I already send an HTTP status code 404):

![Screenshot 2019-09-06 at 17 35 27](https://user-images.githubusercontent.com/1432989/64440790-ea0ae880-d0cc-11e9-830a-24d29724958c.png)
